name = "NLSolvers"
uuid = "337daf1e-9722-11e9-073e-8b9effe078ba"
authors = ["Patrick Kofod Mogensen <patrick.mogensen@gmail.com>"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
